### ISSUE TITLE
Terminal freezes when running my custom action 

### ISSUE THREAD

**Issue by kaushalmodi** [peco/peco#345]
# What is the peco version, OS, architecture? 

- peco version - 0.4.2
- OS - RHEL 6.6
- Terminal - xterm
- Shell - tcsh
- Using in tmux master branch build

# Abstract

My custom action causes `peco` to freeze and in the process of killing the stuck process, I also lose my terminal cursor. So then I eventually need to kill that terminal too.

# Discussion

I have [this custom action named `my.ToggleSelectionInAboveLine`](https://github.com/kaushalmodi/dotfiles/blob/a41ea9d224850bba3470c4238562bfc7779be8f5/.config/peco/config.json#L121-L124), and I have [bound it to `C-u,C-Space`](https://github.com/kaushalmodi/dotfiles/blob/a41ea9d224850bba3470c4238562bfc7779be8f5/.config/peco/config.json#L139).

When I use the `C-u,S-Space` binding, peco freezes, and I need to use `kill -9` to kill it from another terminal. Then the terminal recovers, but I do not see my regular cursor in the terminal any more!

So there are 2 issues:

1. `peco is freezing due to this action:  

   ```
        "my.ToggleSelectionInAboveLine": [
            "peco.SelectUp",
            "peco.ToggleSelectionAndSelectNext"
        ],
    ```

2. After `peco` is killed, I lose the cursor in my terminal.

  This is what a selected terminal (pane, in tmux) looks like normally:

  - Note that the upper terminal is selected and you can see the cursor in that

  ![image](https://cloud.githubusercontent.com/assets/3578197/18960845/190cfccc-8639-11e6-86d1-f6094e014c02.png)

  The bottom terminal is where I had to kill the peco process. Now even though that is selected, you see no cursor in there.

  ![image](https://cloud.githubusercontent.com/assets/3578197/18960902/46b661f4-8639-11e6-8f2a-4d4d8ded923d.png)

# My config
- [full config code](https://github.com/kaushalmodi/dotfiles/blob/master/.config/peco/config.json)

**Comment by lestrrat** [comment]
try to use kill -ABRT, not 9. This way you get a stacktrace which is much more useful.

**Comment by kaushalmodi** [comment]
Thanks.

Here is the backtrace:

```
r12    0x42e140
r13    0x6bd4e4
r14    0x0
r15    0x8
rip    0x45b8a3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by lestrrat** [comment]
hmmm, that seems way too short.

**Comment by kaushalmodi** [comment]
hmm, I realized what happened.. it seems like even though I am running peco in tmux, the backtrace gets truncated to the height of the terminal/pane.

With max terminal height, this is what I got:

Is there a way to create a crashdump file? If it already does, where is it saved?
```
github.com/peco/peco.(*Input).handleInputEvent(0xc820015c20, 0x7f75d6f5a8d8, 0xc820019840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/input.go:74 +0x39b
github.com/peco/peco.(*Input).Loop(0xc820015c20, 0x7f75d6f5a8d8, 0xc820019840, 0xc8200da640, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/input.go:26 +0x1a7
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

goroutine 11 [select]:
github.com/peco/peco.(*View).Loop(0xc8200da700, 0x7f75d6f5a8d8, 0xc820019840, 0xc8200da640, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/view.go:46 +0x610
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

goroutine 12 [select]:
github.com/peco/peco.(*Filter).Loop(0xc8200540d8, 0x7f75d6f5a8d8, 0xc820019840, 0xc8200da640, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/filter.go:163 +0x2a1
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

goroutine 13 [select]:
github.com/peco/peco/sig.(*Handler).Loop(0xc8200da720, 0x7f75d6f5a8d8, 0xc820019840, 0xc8200da640, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/sig/sig.go:44 +0x1e0
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

rax    0xfffffffffffffffc
rbx    0xc820065eb0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x78bbf0
rsi    0x0
rbp    0x0
rsp    0xc820065e78
r8     0x0
r9     0x0
r10    0xc820065eb0
r11    0x246
r12    0x42e140
r13    0x6bd4e4
r14    0x0
r15    0x8
rip    0x45b8a3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by lestrrat** [comment]
The above stacktrace suggest to me that peco was in a normal state. Did you reproduce the problem, and then send `ABRT`?

**Comment by kaushalmodi** [comment]
Yes, I am consistently able to reproduce this problem. Here's from another frozen then kill -ABRT peco instance. This time I ran it directly in uxterm (no tmux) and made the fonts *really* small :)

![image](https://cloud.githubusercontent.com/assets/3578197/18969260/6ffbf8fa-865a-11e6-920f-e27e73192aef.png)


And here is the full backtrace:

```
PC=0x45b8a3 m=1

goroutine 0 [idle]:
runtime.futex(0x78bbf0, 0x0, 0xc820065eb0, 0x0, 0x0, 0x45b6ac, 0x3c, 0x0, 0x40e4eb, 0x78bbf0, ...)
        /home/kmodi/go1.6.2/src/runtime/sys_linux_amd64.s:307 +0x23
runtime.futexsleep(0x78bbf0, 0x0, 0xdf8475800)
        /home/kmodi/go1.6.2/src/runtime/os1_linux.go:57 +0xf0
runtime.notetsleep_internal(0x78bbf0, 0xdf8475800, 0xc820000480)
        /home/kmodi/go1.6.2/src/runtime/lock_futex.go:174 +0x12b
runtime.notetsleep(0x78bbf0, 0xdf8475800, 0xca365124619b6)
        /home/kmodi/go1.6.2/src/runtime/lock_futex.go:194 +0x6b
runtime.sysmon()
        /home/kmodi/go1.6.2/src/runtime/proc.go:3480 +0x487
runtime.mstart1()
        /home/kmodi/go1.6.2/src/runtime/proc.go:1098 +0xec
runtime.mstart()
        /home/kmodi/go1.6.2/src/runtime/proc.go:1068 +0x72

goroutine 1 [chan receive]:
github.com/peco/peco.(*Peco).Run(0xc82003f500, 0x7f8d4fa76030, 0xc8204f8040, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:358 +0xa27
main._main(0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/cmd/peco/peco.go:31 +0xfa
main.main()
        /home/kmodi/go.apps/src/github.com/peco/peco/cmd/peco/peco.go:21 +0x35

goroutine 5 [runnable]:
os/signal.signal_recv(0x7f8d4fcd5078)
        /home/kmodi/go1.6.2/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
        /home/kmodi/go1.6.2/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /home/kmodi/go1.6.2/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x6be8d0, 0xc820052728, 0x658418, 0x6, 0x18, 0x2)
        /home/kmodi/go1.6.2/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820052728, 0x0, 0x18)
        /home/kmodi/go1.6.2/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820052728)
        /home/kmodi/go1.6.2/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
        /home/kmodi/go1.6.2/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
        /home/kmodi/go1.6.2/src/runtime/asm_amd64.s:1998 +0x1

goroutine 14 [select]:
github.com/nsf/termbox-go.Init.func1()
        /home/kmodi/go.apps/src/github.com/nsf/termbox-go/api.go:93 +0x3bc
created by github.com/nsf/termbox-go.Init
        /home/kmodi/go.apps/src/github.com/nsf/termbox-go/api.go:105 +0x8c5

goroutine 33 [select]:
github.com/peco/peco.(*idgen).Run(0xc820054048, 0x7f8d4fa76030, 0xc8204f8040)
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:67 +0x129
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:291 +0x279

goroutine 34 [chan send]:
github.com/peco/peco.(*Termbox).PollEvent.func1(0xc820032480)
        /home/kmodi/go.apps/src/github.com/peco/peco/screen.go:56 +0x9a
created by github.com/peco/peco.(*Termbox).PollEvent
        /home/kmodi/go.apps/src/github.com/peco/peco/screen.go:58 +0x53

goroutine 49 [semacquire]:
sync.runtime_Semacquire(0xc820013b08)
        /home/kmodi/go1.6.2/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820013b04)
        /home/kmodi/go1.6.2/src/sync/mutex.go:83 +0x1c4
github.com/peco/peco/hub.(*Hub).Batch(0xc820013b00, 0xc82006e7a0)
        /home/kmodi/go.apps/src/github.com/peco/peco/hub/hub.go:44 +0x35
github.com/peco/peco.doToggleSelectionAndSelectNext(0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/action.go:355 +0x6c
github.com/peco/peco.ActionFunc.Execute(0x6be458, 0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/action.go:26 +0x4c
github.com/peco/peco.makeCombinedAction.func1.1()
        /home/kmodi/go.apps/src/github.com/peco/peco/action.go:701 +0x10f
github.com/peco/peco/hub.(*Hub).Batch(0xc820013b00, 0xc82006e978)
        /home/kmodi/go.apps/src/github.com/peco/peco/hub/hub.go:55 +0xd0
github.com/peco/peco.makeCombinedAction.func1(0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/action.go:703 +0x9c
github.com/peco/peco.ActionFunc.Execute(0xc820011840, 0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/action.go:26 +0x4c
github.com/peco/peco.wrapClearSequence.func1(0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/keymap.go:96 +0x281
github.com/peco/peco.ActionFunc.Execute(0xc820010a80, 0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/action.go:26 +0x4c
github.com/peco/peco.Keymap.ExecuteAction(0xc820012a50, 0xc820012f90, 0x7f8d4fcd96a0, 0xc820014a40, 0x0, 0x7f8d4fa76030, 0xc8204f8040, 0xc82003f500, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/keymap.go:34 +0x166
github.com/peco/peco.(*Input).handleInputEvent(0xc820012750, 0x7f8d4fa76030, 0xc8204f8040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/kmodi/go.apps/src/github.com/peco/peco/input.go:74 +0x39b
github.com/peco/peco.(*Input).Loop(0xc820012750, 0x7f8d4fa76030, 0xc8204f8040, 0xc820010860, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/input.go:26 +0x1a7
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

goroutine 50 [select]:
github.com/peco/peco.(*View).Loop(0xc820010a60, 0x7f8d4fa76030, 0xc8204f8040, 0xc820010860, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/view.go:46 +0x610
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

goroutine 51 [select]:
github.com/peco/peco.(*Filter).Loop(0xc820054000, 0x7f8d4fa76030, 0xc8204f8040, 0xc820010860, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/filter.go:163 +0x2a1
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

goroutine 52 [select]:
github.com/peco/peco/sig.(*Handler).Loop(0xc8200da020, 0x7f8d4fa76030, 0xc8204f8040, 0xc820010860, 0x0, 0x0)
        /home/kmodi/go.apps/src/github.com/peco/peco/sig/sig.go:44 +0x1e0
created by github.com/peco/peco.(*Peco).Run
        /home/kmodi/go.apps/src/github.com/peco/peco/peco.go:308 +0x7f1

rax    0xfffffffffffffffc
rbx    0xc820065eb0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x78bbf0
rsi    0x0
rbp    0x0
rsp    0xc820065e78
r8     0x0
r9     0x0
r10    0xc820065eb0
r11    0x246
r12    0x42e140
r13    0x6bd4e4
r14    0x0
r15    0x8
rip    0x45b8a3
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by kaushalmodi** [comment]
That said, does this custom action run fine for you?

```
"my.ToggleSelectionInAboveLine": [
        "peco.SelectUp",
        "peco.ToggleSelectionAndSelectNext"
    ],
```

**Comment by lestrrat** [comment]
Okay, so a couple of things:

* Your stacktrace is now "correct", there's a problem (i.e., your previous stacktrace was generated when the problem was NOT manifesting)
* In general, please use the binary builds, as Go version and dependency version cannot be guaranteed

Having said that, I see the problem. I don't know exactly when I will get around to it, but please give me a bit of time

**Comment by lestrrat** [comment]
@kaushalmodi if you know how to do this, would be nice if you can test out the` topic/issue-345` branch and see if the problem is gone.

**Comment by kaushalmodi** [comment]
> if you know how to do this, would be nice if you can test out thetopic/issue-345 branch 

Can I please get some help here?

## Attempt 1 - Try building locally after switching to experimental branch

```
km²~/downloads/:git/peco> git checkout topic/issue-345
Branch topic/issue-345 set up to track remote branch topic/issue-345 from origin.
Switched to a new branch 'topic/issue-345'
km²~/downloads/:git/peco> git status
On branch topic/issue-345
Your branch is up-to-date with 'origin/topic/issue-345'.
nothing to commit, working tree clean
km²~/downloads/:git/peco> go build
package .
        imports github.com/peco/peco/internal/keyseq: use of internal package not allowed
package .
        imports github.com/peco/peco/internal/util: use of internal package not allowed
```

## Attempt 2 - Commit the experimental commit to my fork and go get from there

```
km²~/downloads/:git> go get -u -v github.com/kaushalmodi/peco/cmd/peco
github.com/kaushalmodi/peco (download)
github.com/peco/peco (download)
github.com/google/btree (download)
github.com/jessevdk/go-flags (download)
github.com/lestrrat/go-pdebug (download)
github.com/mattn/go-runewidth (download)
github.com/nsf/termbox-go (download)
github.com/pkg/errors (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
package github.com/kaushalmodi/peco/cmd/peco
        imports github.com/peco/peco/internal/util: use of internal package not allowed
```

**Comment by lestrrat** [comment]
Sure! Short answer: https://github.com/peco/peco#hacking
What it says in that link is, basically, use glide https://github.com/Masterminds/glide/releases/tag/v0.12.2 to get deps, and then build cmd/peco/peco.go (NOT `go build .`)

**Comment by kaushalmodi** [comment]
> use glide ..

Looks like I need to install https://github.com/Masterminds/glide

I'll see if I can test this out over the weekend.

**Comment by kaushalmodi** [comment]
Bummer, I tried installing `glide` and now I face this issue:

```
km²~/downloads/:git/glide> which go                                                                                 09/30 5:23pm
/home/kmodi/go1.7.1/bin/go
km²~/downloads/:git/glide> make build                                                                               09/30 5:23pm
go build -o glide -ldflags "-X main.version=v0.12.1-16-gbd55e76" glide.go
glide.go:24:2: cannot find package "github.com/Masterminds/glide/action" in any of:
        /home/kmodi/go1.7.1/src/github.com/Masterminds/glide/action (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/Masterminds/glide/action (from $GOPATH)
glide.go:25:2: cannot find package "github.com/Masterminds/glide/cache" in any of:
        /home/kmodi/go1.7.1/src/github.com/Masterminds/glide/cache (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/Masterminds/glide/cache (from $GOPATH)
glide.go:26:2: cannot find package "github.com/Masterminds/glide/msg" in any of:
        /home/kmodi/go1.7.1/src/github.com/Masterminds/glide/msg (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/Masterminds/glide/msg (from $GOPATH)
glide.go:27:2: cannot find package "github.com/Masterminds/glide/path" in any of:
        /home/kmodi/go1.7.1/src/github.com/Masterminds/glide/path (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/Masterminds/glide/path (from $GOPATH)
glide.go:28:2: cannot find package "github.com/Masterminds/glide/repo" in any of:
        /home/kmodi/go1.7.1/src/github.com/Masterminds/glide/repo (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/Masterminds/glide/repo (from $GOPATH)
glide.go:29:2: cannot find package "github.com/Masterminds/glide/util" in any of:
        /home/kmodi/go1.7.1/src/github.com/Masterminds/glide/util (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/Masterminds/glide/util (from $GOPATH)
glide.go:31:2: cannot find package "github.com/codegangsta/cli" in any of:
        /home/kmodi/go1.7.1/src/github.com/codegangsta/cli (from $GOROOT)
        /home/kmodi/go.apps/src/github.com/codegangsta/cli (from $GOPATH)
make: *** [build] Error 1
```

I also updated to the latest stable release of go: 1.7.1

From the `glide` github page, I followed these steps:

> To build from source you can: 
> 1. Clone this repository into $GOPATH/src/github.com/Masterminds/glide and change directory into it 
> 2. If you are using Go 1.5 ensure the environment variable GO15VENDOREXPERIMENT is set, for example by running export GO15VENDOREXPERIMENT=1. In Go 1.6 it is enabled by default and in Go 1.7 it is always enabled without the ability to turn it off. 
> 3. Run make build

**Comment by kaushalmodi** [comment]
I already got glide installed and it's in my `$PATH`.

Sorry, still no luck with getting the local build working:

Does the `[WARN]` in the below messages mean anything serious?

```
km²~/downloads/:git/peco_orig> make installdeps
Installing glide for linux/amd64...
linux-amd64/
linux-amd64/glide
linux-amd64/LICENSE
linux-amd64/README.md
Installing dependencies...
[WARN] The name listed in the config file (github.com/peco/peco) does not match the current location (.)
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/google/btree.
[INFO] Fetching updates for github.com/jessevdk/go-flags.
[INFO] Fetching updates for github.com/mattn/go-runewidth.
[INFO] Fetching updates for github.com/nsf/termbox-go.
[INFO] Fetching updates for github.com/pkg/errors.
[INFO] Fetching updates for github.com/davecgh/go-spew.
[INFO] Fetching updates for github.com/lestrrat/go-pdebug.
[INFO] Fetching updates for github.com/stretchr/testify.
[INFO] Fetching updates for golang.org/x/net.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[INFO] Setting version for github.com/davecgh/go-spew to 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d.
[INFO] Setting version for github.com/google/btree to 00edb8c3163323f673bbe3c04afd9429eb12117d.
[INFO] Setting version for github.com/lestrrat/go-pdebug to 2e6eaaa5717f81bda41d27070d3c966f40a1e75f.
[INFO] Setting version for github.com/nsf/termbox-go to 362329b0aa6447eadd52edd8d660ec1dff470295.
[INFO] Setting version for github.com/stretchr/testify to 6cb3b85ef5a0efef77caef88363ec4d4b5c0976d.
[INFO] Setting version for github.com/pkg/errors to d814416a46cbb066b728cfff58d30a986bc9ddbe.
[INFO] Setting version for github.com/jessevdk/go-flags to 6b9493b3cb60367edd942144879646604089e3f7.
[INFO] Setting version for github.com/mattn/go-runewidth to d6bea18f789704b5f83375793155289da36a3c7f.
[INFO] Setting version for golang.org/x/net to ef00b378c73f107bf44d5c9b69875255ce89b79a.
km²~/downloads/:git/peco_orig> make test                                                                            09/30 5:57pm
Installing dependencies...
[WARN] The name listed in the config file (github.com/peco/peco) does not match the current location (.)
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/jessevdk/go-flags.
[INFO] Fetching updates for github.com/lestrrat/go-pdebug.
[INFO] Fetching updates for github.com/nsf/termbox-go.
[INFO] Fetching updates for github.com/pkg/errors.
[INFO] Fetching updates for github.com/stretchr/testify.
[INFO] Fetching updates for github.com/davecgh/go-spew.
[INFO] Fetching updates for github.com/mattn/go-runewidth.
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for github.com/google/btree.
[INFO] Downloading dependencies. Please wait...
[INFO] Setting references.
[INFO] Setting version for github.com/mattn/go-runewidth to d6bea18f789704b5f83375793155289da36a3c7f.
[INFO] Setting version for github.com/lestrrat/go-pdebug to 2e6eaaa5717f81bda41d27070d3c966f40a1e75f.
[INFO] Setting version for github.com/nsf/termbox-go to 362329b0aa6447eadd52edd8d660ec1dff470295.
[INFO] Setting version for github.com/pkg/errors to d814416a46cbb066b728cfff58d30a986bc9ddbe.
[INFO] Setting version for github.com/google/btree to 00edb8c3163323f673bbe3c04afd9429eb12117d.
[INFO] Setting version for github.com/stretchr/testify to 6cb3b85ef5a0efef77caef88363ec4d4b5c0976d.
[INFO] Setting version for github.com/jessevdk/go-flags to 6b9493b3cb60367edd942144879646604089e3f7.
[INFO] Setting version for github.com/davecgh/go-spew to 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d.
[INFO] Setting version for golang.org/x/net to ef00b378c73f107bf44d5c9b69875255ce89b79a.
Running tests...
package ./cmd/peco
        imports github.com/peco/peco/internal/util: use of internal package not allowed
package .
        imports github.com/peco/peco/internal/keyseq: use of internal package not allowed
package .
        imports github.com/peco/peco/internal/util: use of internal package not allowed
make: *** [test] Error 1
```

**Comment by kaushalmodi** [comment]
OK, you need to update the `Hacking` section saying that the `make` steps need to be run from the `${GOPATH}/src/github.com/peco/peco/` directory. Finally got ride of the "internal pacakge not allowed" issue.

But then I ran `make test`, and it failed. Here is the [full log](https://gist.github.com/kaushalmodi/b7e25e8123ab136d50b2ebaa4e31d9b0).

`make build` worked!

And.. I confirm that the `peco` freezing bug is gone!

**Comment by lestrrat** [comment]
> OK, you need to update the `Hacking` section saying that the `make` steps need to be run from the `${GOPATH}/src/github.com/peco/peco/` directory.

Hmm? Where did *YOU* run it from? I mean, there's only one Makefile in the project, which is sort of a give away. I'm just asking to understand the logic.

**Comment by kaushalmodi** [comment]
Not familiar with the go project building methodology, I ran the `make` command from wherever I cloned the peco git repo.

I like to have all my git cloned projects in `~/downloads/git/`. I clone emacs, tmux, and many other git projects to the same directory, and `make` runs fine in those. It is agnostic to the absolute path. 

But it looks like the go projects need to be specifically in `$GOPATH/src/..`. Or is it specifically for only this project?

**Comment by kaushalmodi** [comment]
Thanks for fixing this! :)

**Comment by lestrrat** [comment]
Go projects need a proper $GOPATH, yes. I guess that's sort of the confusion you had.
While I understand the frustration you may have felt, If I start documenting that stuff I'm going to have to pretty much explain the entire mechanism behind how go builds work, so I think I'm going to skip on updating the README there ;)
