### ISSUE TITLE
Peco all of a sudden start throwing "panic" and crashing

### ISSUE THREAD

**Issue by OmanF** [peco/peco#510]
# What is the peco version, OS, architecture? 
0.5.1, Linux Debian Sid, AMD64

# Abstract
After updating the entire system today (`apt update && apt upgrade`), Peco, that worked great up till now, stopped working and starts throwing the following runtime panic, and crashing (example command: `ls -alhF | peco`):

```
panic: runtime error: index out of range

goroutine 9 [running]:
github.com/nsf/termbox-go.send_attr(0x0)
        github.com/nsf/termbox-go/termbox.go:154 +0x359
github.com/nsf/termbox-go.send_clear(0x723a80, 0x71)
        github.com/nsf/termbox-go/termbox.go:243 +0x3d
github.com/nsf/termbox-go.update_size_maybe(0x2e0000002e, 0x0)
        github.com/nsf/termbox-go/termbox.go:267 +0xb0
github.com/nsf/termbox-go.Flush(0xc000000008, 0x5d36a8)
        github.com/nsf/termbox-go/api.go:156 +0x3c
github.com/peco/peco.(*Termbox).Flush(0xc000098200, 0x0, 0x0)
        github.com/peco/peco/screen.go:48 +0x64
github.com/peco/peco.(*StatusBar).PrintStatus(0xc00000a120, 0x5cb809, 0x0, 0x0)
        github.com/peco/peco/layout.go:270 +0x1e7
github.com/peco/peco.(*View).printStatus(0xc00000a1a0, 0x5f5000, 0xc000098d80, 0x7fb41fd53f90, 0xc000098d60)
        github.com/peco/peco/view.go:74 +0xbf
github.com/peco/peco.(*View).Loop(0xc00000a1a0, 0x5f59c0, 0xc0000aebc0, 0xc000098d20, 0x0, 0x0)
        github.com/peco/peco/view.go:50 +0x491
created by github.com/peco/peco.(*Peco).Run.func4
        github.com/peco/peco/peco.go:346 +0x1bd
```

**Comment by OmanF** [comment]
Strange: updating through `apt` doesn't update to the latest version of `Peco` which is 0.5.8.
Using the binary from the download section works great!

Closing as it seems this is solved in the most up-to-date version.
