### ISSUE TITLE
panic and crashing with index out of range

### ISSUE THREAD

**Issue by amdemas** [peco/peco#516]
# What is the peco version, OS, architecture? 

peco version v0.5.8 (built with go1.14.2)  <- Pulled from the releases page
Fedora 33

# Abstract
Every time peco is called it fails

# Discussion

Here is the output of the failure
```
panic: runtime error: index out of range [2] with length 0

goroutine 26 [running]:
github.com/nsf/termbox-go.SetCursor(0x6, 0x0)
	/Users/lestrrat/dev/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/api.go:214 +0x16e
github.com/peco/peco.(*Termbox).SetCursor(0xc00000c240, 0x6, 0x0)
	/Users/lestrrat/dev/src/github.com/peco/peco/screen.go:38 +0x35
github.com/peco/peco.UserPrompt.Draw(0xc0001801c0, 0x7ffe55b90be7, 0x5, 0x5, 0xc00014434a, 0xc000144000)
	/Users/lestrrat/dev/src/github.com/peco/peco/layout.go:189 +0x3ce
github.com/peco/peco.(*BasicLayout).DrawPrompt(...)
	/Users/lestrrat/dev/src/github.com/peco/peco/layout.go:672
github.com/peco/peco.(*BasicLayout).DrawScreen(0xc000180200, 0xc000144000, 0x0)
	/Users/lestrrat/dev/src/github.com/peco/peco/layout.go:688 +0xb4
github.com/peco/peco.(*View).drawScreen(0xc000180220, 0x621700, 0xc0001800e0, 0x0)
	/Users/lestrrat/dev/src/github.com/peco/peco/view.go:86 +0x76
github.com/peco/peco.(*View).Loop(0xc000180220, 0x6221c0, 0xc000110c40, 0xc00000ce60, 0x0, 0x0)
	/Users/lestrrat/dev/src/github.com/peco/peco/view.go:66 +0x376
created by github.com/peco/peco.(*Peco).Run.func4
	/Users/lestrrat/dev/src/github.com/peco/peco/peco.go:369 +0x1ed
```

Here is a sample of what is being called

```
function peco-ssh {
  local host=$(grep '^Host' ~/.ssh/config | awk '{ print $2 }' | peco --prompt '[ssh]')
  if [ -n "${host}" ]; then
    echo "ssh ${host}"
    \ssh ${host}
  fi
}
alias pssh='peco-ssh'
````

**Comment by syohex** [comment]
Could you tell us output of `grep '^Host' ~/.ssh/config` for reproducing this issue ?

**Comment by amdemas** [comment]
Hey @syohex 

The output is 

```
Host github.com
Host home
Host dev
```

I have been messing with it for a bit and also noticed that my $TERM was set to `alacritty` so forcing to `xterm-256color` seems to have fixed the issue. But I guess the question now would be why such a vague error? It should probably error with "Unsupported terminal".

**Comment by syohex** [comment]
Thanks for your information. I can reproduce this by setting `TERM` environment value `alacritty`. I suppose that this is `termbox-go` issue. However it is no longer maintained. I suppose we need to replace `termbox-go` with [tcell](https://github.com/gdamore/tcell). It looks `tcell` supports [alacritty](https://github.com/gdamore/tcell/blob/50e36d6c03cf46b6bc4a7601fa45e1f67f507cd1/terminfo/a/alacritty/term.go)

**Comment by lestrrat** [comment]
I had a branch with tcell somewhere, but it has been a lomg time. I need to look for it and refresh my memory

**Comment by syohex** [comment]
I have tried to replace with `tcell` by using its `termbox` compatible layer. It looks working well, however unit tests are crashed by segmentation fault. Something is wrong.

**Comment by szaffarano** [comment]
I'm having the same issue,
- kitty 0.25.2
- tmux 3.3a
not using tmux fix the problem.

```sh
$ ls | peco
panic: runtime error: index out of range [5] with length 0

goroutine 52 [running]:
github.com/nsf/termbox-go.send_attr(0x0)
        /home/lestrrat/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:162 +0x3bf
github.com/nsf/termbox-go.send_clear(0x6be060, 0x13f)
        /home/lestrrat/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:248 +0x3d
github.com/nsf/termbox-go.update_size_maybe(0x1, 0xc00019f498)
        /home/lestrrat/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/termbox.go:272 +0xc5
github.com/nsf/termbox-go.Flush(0x2e00000074, 0x2e0000002e)
        /home/lestrrat/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20190817171036-93860e161317/api.go:165 +0x3c
github.com/peco/peco.(*Termbox).Flush(0xc0000ae0c0, 0x0, 0x0)
        /home/lestrrat/dev/src/github.com/peco/peco/screen.go:52 +0x68
github.com/peco/peco.(*StatusBar).PrintStatus(0xc00025a060, 0x5aee3e, 0x0, 0x0)
        /home/lestrrat/dev/src/github.com/peco/peco/layout.go:279 +0x1ea
github.com/peco/peco.(*View).printStatus(0xc00025e048, 0x5e10d8, 0xc0000cc6c0, 0x7fdee057e008, 0xc0000ae5b8)
        /home/lestrrat/dev/src/github.com/peco/peco/view.go:74 +0xbe
github.com/peco/peco.(*View).Loop(0xc00025e048, 0x5e16f8, 0xc0000c0c40, 0xc0000ae570, 0x0, 0x0)
        /home/lestrrat/dev/src/github.com/peco/peco/view.go:50 +0x26f
created by github.com/peco/peco.(*Peco).Run.func4
        /home/lestrrat/dev/src/github.com/peco/peco/peco.go:369 +0x225
```

**Comment by syohex** [comment]
@szaffarano Could you try to unset `TERMINFO` environment variable ? The details are #535

**Comment by szaffarano** [comment]
Hi @syohex unsetting `TERMINFO` works ok!
Thanks

**Comment by silverhook** [comment]
I can reproduce the issue in:

- Konsole 25.04
- connected to Debian server over SSH with
  - Fish 3.6.0
  - Tmux 3.3a
  - `$TERM=tmux-256color`
  - `$TERMIMFO=`

Interestingly enough, in the following set-up it works fine (i.e. from the same Arch laptop, but not using SSH)

- Konsole 25.04
- Fish 4.0.2
- Tmux 3.5_a
- `$TERM=xterm-256color`
- `$TERMIMFO=`
