### ISSUE TITLE
Not parsing keyboard input on FreeBSD 13

### ISSUE THREAD

**Issue by Dautor** [peco/peco#521]
# What is the peco version, OS, architecture? 

peco version v0.5.8 (built with go1.16.3)
OS: FreeBSD 13.0-RELEASE
Architecture: amd64

# Abstract

Peco unusable on FreeBSD 13 because it fails to be interactive.

# Discussion

It does not react to any keystroke and I'm forced to kill it to make the terminal usable again.
After it is killed I can see the text that was supposed to be sent to it.
The same issue is present with `peco-0.4.4_1` installed with pkg.
I tested it with `xterm` and `st` to test whether it was a terminal emulator related issue.
I tested it with `sh`, `bash` and `fish` to test whether it was a shell related issue.

terminal 1:
`$ echo a | peco`
keystrokes 'asdf' (nothing is happening with peco)
terminal 2:
`$ killall peco`
terminal 1:
says peco was killed and `$ asdf` appears

**Comment by lestrrat** [comment]
Hmmm, hard to say. Can you try `kill -ABRT $pid_of_peco` and capture the stacktrace?

**Comment by Dautor** [comment]
I also tested it on a Raspberry Pi 3B running FreeBSD 13-CURRENT and it shows the same behavior as described above.

Here is the stacktrace:
```
SIGABRT: abort
PC=0x7004c m=0 sigcode=65537

goroutine 0 [idle]:
runtime.sys_umtx_op(0x29f2d8, 0xf, 0x18, 0x0, 0x0, 0x19d94, 0x4000034558, 0x100000010, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/sys_freebsd_arm64.s:63 +0x1c
runtime.futexsleep1(0x29f2d8, 0x0, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_freebsd.go:168 +0x88
runtime.futexsleep.func1()
        /usr/local/go/src/runtime/os_freebsd.go:156 +0x30
runtime.futexsleep(0x29f2d8, 0x4000000000, 0xffffffffffffffff)
        /usr/local/go/src/runtime/os_freebsd.go:155 +0x40
runtime.notesleep(0x29f2d8)
        /usr/local/go/src/runtime/lock_futex.go:159 +0x90
runtime.mPark()
        /usr/local/go/src/runtime/proc.go:1340 +0x20
runtime.stoplockedm()
        /usr/local/go/src/runtime/proc.go:2451 +0x48
runtime.schedule()
        /usr/local/go/src/runtime/proc.go:3059 +0x420
runtime.park_m(0x4000082480)
        /usr/local/go/src/runtime/proc.go:3274 +0x80
runtime.mcall(0xffff01ff)
        /usr/local/go/src/runtime/asm_arm64.s:185 +0x58

goroutine 1 [chan receive]:
github.com/peco/peco.(*Peco).Run(0x400009f500, 0x66f19008, 0x40000ae010, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:367 +0x4dc
main._main(0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/cmd/peco/peco.go:31 +0xa0
main.main()
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/cmd/peco/peco.go:21 +0x34

goroutine 33 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:168 +0xc0
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x18
created by os/signal.Notify.func1.1
        /usr/local/go/src/os/signal/signal.go:151 +0x38

goroutine 19 [select]:
github.com/peco/peco/vendor/github.com/nsf/termbox-go.Init.func1()
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/vendor/github.com/nsf/termbox-go/api.go:86 +0x234
created by github.com/peco/peco/vendor/github.com/nsf/termbox-go.Init
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/vendor/github.com/nsf/termbox-go/api.go:83 +0x668

goroutine 20 [select]:
github.com/peco/peco.(*idgen).Run(0x40000b2038, 0x66f1d058, 0x40000b6b00)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:67 +0xa0
created by github.com/peco/peco.(*Peco).Run
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:297 +0x1e0

goroutine 21 [select]:
github.com/peco/peco/vendor/github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/vendor/github.com/nsf/termbox-go/api.go:320 +0x180
github.com/peco/peco.(*Termbox).PollEvent.func1(0x4000094660)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/screen.go:56 +0x58
created by github.com/peco/peco.(*Termbox).PollEvent
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/screen.go:52 +0x48

goroutine 5 [select]:
github.com/peco/peco.(*Input).Loop(0x40000991d0, 0x66f1d058, 0x40000b6b00, 0x40000a64c8, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/input.go:22 +0xa8
created by github.com/peco/peco.(*Peco).Run
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:314 +0x404

goroutine 6 [runnable]:
github.com/peco/peco/vendor/github.com/mattn/go-runewidth.(*Condition).RuneWidth(0x2cbe60, 0x20, 0x1)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/vendor/github.com/mattn/go-runewidth/runewidth.go:322 +0x1c8
github.com/peco/peco/vendor/github.com/mattn/go-runewidth.RuneWidth(...)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/vendor/github.com/mattn/go-runewidth/runewidth.go:436
github.com/peco/peco/vendor/github.com/nsf/termbox-go.Flush(0x1c0668, 0x40000ae248)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/vendor/github.com/nsf/termbox-go/api.go:167 +0xfc
github.com/peco/peco.(*Termbox).Flush(0x40000ae248, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/screen.go:35 +0x74
github.com/peco/peco.UserPrompt.Draw(0x40000c0640, 0x18ad40, 0x6, 0x6, 0x400009f7f2, 0x400009f500)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/layout.go:192 +0x464
github.com/peco/peco.(*BasicLayout).DrawPrompt(...)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/layout.go:612
github.com/peco/peco.(*BasicLayout).DrawScreen(0x40000a64e0, 0x400009f500, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/layout.go:628 +0x88
github.com/peco/peco.(*View).drawScreen(0x40000a64f8, 0x1be8c8, 0x4000218408, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/view.go:86 +0x68
github.com/peco/peco.(*View).Loop(0x40000a64f8, 0x66f1d058, 0x40000b6b00, 0x40000a64c8, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/view.go:66 +0x348
created by github.com/peco/peco.(*Peco).Run
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:314 +0x404

goroutine 7 [select]:
github.com/peco/peco.(*Filter).Loop(0x40000b20b8, 0x66f1d058, 0x40000b6b00, 0x40000a64c8, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/filter.go:163 +0x14c
created by github.com/peco/peco.(*Peco).Run
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:314 +0x404

goroutine 8 [select]:
github.com/peco/peco/sig.(*Handler).Loop(0x400000c018, 0x66f1d058, 0x40000b6b00, 0x40000a64c8, 0x0, 0x0)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/sig/sig.go:44 +0x94
created by github.com/peco/peco.(*Peco).Run
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:314 +0x404

goroutine 9 [runnable]:
context.(*cancelCtx).Done(0x40000b6b00, 0x4000061e08)
        /usr/local/go/src/context/context.go:360 +0x15c
github.com/peco/peco.(*Source).Setup.func1()
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/source.go:102 +0x24c
sync.(*Once).doSlow(0x4000064080, 0x4000032f80)
        /usr/local/go/src/sync/once.go:68 +0x100
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/peco/peco.(*Source).Setup(0x4000064000, 0x66f1d058, 0x40000b6b00, 0x400009f500)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/source.go:34 +0x78
created by github.com/peco/peco.(*Peco).SetupSource
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/peco.go:432 +0x1bc

goroutine 10 [select]:
github.com/peco/peco.(*Source).Setup.func1.2(0x40000181e0, 0x195b50, 0x400009f500)
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/source.go:52 +0xac
created by github.com/peco/peco.(*Source).Setup.func1
        /wrkdirs/usr/ports/textproc/peco/work/src/github.com/peco/peco/source.go:47 +0xfc

r0      0x4
r1      0xf
r2      0x0
r3      0x18
r4      0x0
r5      0x29edc0
r6      0x8
r7      0x1
r8      0x1c6
r9      0x40000580a0
r10     0x2
r11     0x400002cf8c
r12     0x1
r13     0x40000945a0
r14     0x4000094600
r15     0x0
r16     0x0
r17     0x7
r18     0x0
r19     0x402e0000
r20     0x1c0950
r21     0x400002ce30
r22     0x0
r23     0x0
r24     0x0
r25     0x0
r26     0xffffffffe928
r27     0x294dc0
r28     0x29edc0
r29     0xffffffffe908
lr      0x3c3a8
sp      0xffffffffe880
pc      0x7004c
fault   0x0
```

**Comment by lestrrat** [comment]
Hmmm, I'm a bit stumped. Just for sanity's sake, does the official releas... ah... we don't provide the freebsd binaries, eh?

Well, in that case, have you tried upgrading the `github.com/nsf/termbox-go` library? That's where I would initially suspect.

**Comment by Dautor** [comment]
Changing from `github.com/nsf/termbox-go v0.0.0-20190817171036-93860e161317` to `github.com/nsf/termbox-go v1.1.0` in `go.mod` fixes the issue.
Also, could there be added a binary release for FreeBSD? Version 0.4.4 can be downloaded using `pkg`, but I assume it is using the old version of `termbox-go`.

**Comment by Dautor** [comment]
Well... it seems like it fixes only the intractability side.
Anything I select produces this error. It happens even if I only try to exit using ESC key.
```
$ echo a | peco
Error:
runtime error: index out of range [14] with length 14⏎
```
